# Generated by Django 3.1 on 2021-07-20 08:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objacts', django.db.models.manager.Manager()),
            ],
        ),
    ]
